### ISSUE TITLE
How to build the source in Eclipse?

### ISSUE THREAD

**Issue by hegdemk2004** [bmTas/cb2xml#4]
Hi, I would like to try this out. There is no jar file in the download. So I need to build it right? I tried importing  Source folder as Cb2xml-/Source folder (where I can see the .pom file) as "existing Maven project" into Eclipse. It does import and build, but I am not getting the "Run As -> Java Application" option at all. Kindly you please suggest what is the right folder to import ?

**Comment by hegdemk2004** [comment]
..and I could not find the JAR files mentioned in this command - either in the downloaded Git Repo or after importing and building the project in Eclipse.. java -cp ../../lib/cb2xml.jar:../../lib/cb2xml_Jaxb.jar:./cb2xml_example.jar net.sf.cb2xml.example.DemoCobolJTreeTable cbl2xml_Test102.cbl

**Comment by bmTas** [comment]
You can download from sourceforge: https://sourceforge.net/projects/cb2xml/files/cb2xml/


For maven you can do

   Run As -> Maven build  - to build jars and run JUnit tests

  Run As -> Maven install same as build + copy jars into mavens local repositry
