### ISSUE TITLE
Display-length computed wrong in case of nested structure

### ISSUE THREAD

**Issue by Demo30** [bmTas/cb2xml#5]
Hello, the display-length value for MYOBJ seems be computed incorrectly. In case of nested structures, the display-length seem to be always the same as storage-length. In given example display-length of 9 for MYOBJ seems to be the correct value.

```
<item display-length="8" level="01" name="MYOBJ" position="1" storage-length="8">
  <item display-length="2" level="05" name="SUBA" numeric="true" picture="99" position="1" storage-length="2" usage="computational-3" />
  <item display-length="2" level="05" name="SUBB" numeric="true" picture="99" position="3" storage-length="2" usage="computational-3" />
  <item display-length="4" level="05" name="SUBC" numeric="true" picture="9(4)" position="5" storage-length="3" usage="computational-3" />
  <item display-length="1" level="05" name="SUBD" picture="X" position="9" storage-length="1" />
</item>
```

**Comment by bmTas** [comment]
Will investigate

**Comment by bmTas** [comment]
Which version of cb2xml are you using. This was an issue earlier versions of cb2xml. I could not replicate it in my copy ???

**Comment by Demo30** [comment]
You are right, i was indeed using an old version (0.95.1), the result is correct in 1.01.2. Sorry for wasting your time.
